export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

export const CONFIRM_ORDERS_REQUEST = 'CONFIRM_ORDERS_REQUEST';
export const CONFIRM_ORDERS_SUCCESS = 'CONFIRM_ORDERS_SUCCESS';
export const CONFIRM_ORDERS_FAILURE = 'CONFIRM_ORDERS_FAILURE';

export const PLACED_ORDERS_REQUEST = 'PLACED_ORDERS_REQUEST';
export const PLACED_ORDERS_SUCCESS = 'PLACED_ORDERS_SUCCESS';
export const PLACED_ORDERS_FAILURE = 'PLACED_ORDERS_FAILURE';

export const DELIVERED_ORDERS_REQUEST = 'DELIVERED_ORDERS_REQUEST';
export const DELIVERED_ORDERS_SUCCESS = 'DELIVERED_ORDERS_SUCCESS';
export const DELIVERED_ORDERS_FAILURE = 'DELIVERED_ORDERS_FAILURE';

export const DELETE_ORDERS_REQUEST = 'DELETE_ORDERS_REQUEST';
export const DELETE_ORDERS_SUCCESS = 'DELETE_ORDERS_SUCCESS';
export const DELETE_ORDERS_FAILURE = 'DELETE_ORDERS_FAILURE';

export const SHIP_ORDERS_REQUEST = 'SHIP_ORDERS_REQUEST';
export const SHIP_ORDERS_SUCCESS = 'SHIP_ORDERS_SUCCESS';
export const SHIP_ORDERS_FAILURE = 'SHIP_ORDERS_FAILURE';
