export const FIND_USER_BY_ID_REQUEST = 'FIND_USER_BY_ID_REQUEST';
export const FIND_USER_BY_ID_SUCCESS = 'FIND_USER_BY_ID_SUCCESS';
export const FIND_USER_BY_ID_FAILURE = 'FIND_USER_BY_ID_FAILURE';

export const FIND_USER_REQUEST = 'FIND_USER_REQUEST';
export const FIND_USER_SUCCESS = 'FIND_USER_SUCCESS';
export const FIND_USER_FAILURE = 'FIND_USER_FAILURE';


export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
